### ISSUE TITLE
How to make a video source for a MediaSource Object

### ISSUE THREAD

**Issue by amanlol101** [samdutton/simpl#118]
I'm trying to make my own Media Player using the Media Source Extensions API. I have downloaded an example from MDN Web Doc which include a video source 'frag-bunny' and a HTML Script. When I run the Script it plays the video perfectly but when I change the video source, the another .mp4 file, it does not work. I want to know how to create a .mp4 file which is compatible with this script: http://nickdesaulniers.github.io/netfix/demo/bufferAll.html . Thanks

**Comment by samdutton** [comment]
Hi — won't have a chance to look into this, but you might want to take a
look at https://bit.ly/pwa-media.

On 12 Apr 2018 04:46, "amanlol101" <notifications@github.com> wrote:

I'm trying to make my own Media Player using the Media Source Extensions
API. I have downloaded an example from MDN Web Doc which include a video
source 'frag-bunny' and a HTML Script. When I run the Script it plays the
video perfectly but when I change the video source, the another .mp4 file,
it does not work. I want to know how to create a .mp4 file which is
compatible with this script:
http://nickdesaulniers.github.io/netfix/demo/bufferAll.html . Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/samdutton/simpl/issues/118>, or mute the thread
