### ISSUE TITLE
No transparent background on Android 7.x

### ISSUE THREAD

**Issue by a-klimashevsky** [samdutton/simpl#124]
I have Samsung S6 with Android 7.0 and Sony Z3+ with Android 7.1
soccer is ok with transparent bg, but dancer with gray one.
What is the different in encoding?

**Comment by samdutton** [comment]
Thanks for the heads-up.

I did this demo ages ago — I'll see if someone can help me sort it out.

**Comment by Florianirex** [comment]
Hey @samdutton, any updates on this?
I have the same problem on Chrome 71, Oneplus 5, Android 8.1.0 
Dancer is gray, soccer is transparant.Maybe something to do with VP8 vs VP9? 

Came here because i made a video for our homepage www.hq.app -> black background on chrome mobile. On desktop it works fine.

**Comment by dangkhuat** [comment]
Hey @samdutton, any updates on this please?
I got the same problem on Chrome 68, Pixel, Android 9.0.
Thanks.

**Comment by samdutton** [comment]
I haven't really worked on media stuff for a couple of years, but there's lots of good stuff in [this thread](https://groups.google.com/a/google.com/forum/#!topic/vpx-eng/SCBdY56KKmw). 

Here are some highlights:
• Alpha in WebM [explained](http://wiki.webmproject.org/alpha-channel).
• [Readme for encode wrapper in WebM](https://chromium.googlesource.com/webm/webm-tools/+/master/alpha_encoder/README).

Best place to ask for more information is [webm-discuss](https://groups.google.com/a/webmproject.org/forum/#!forum/webm-discuss)
