### ISSUE TITLE
Not able to run samdutton/simpl/Devicejs

### ISSUE THREAD

**Issue by KrishPS** [samdutton/simpl#59]
Hi,
I am new for JS. I tried to run Devicejs. But gave me the error Uncaught ReferenceError: module is not defined at like "module.exports = require("js/lib/Device.js");"?

As per my understanding, it detects all attached devices. Please correct me if I am wrong.
Thanks in Advnace

**Comment by samdutton** [comment]
Hi – thanks for this.

Device.js seems to have changed name: I could find [github.com/uupaa/DeviceQuery.js](https://github.com/uupaa/DeviceQuery.js). There's [another project](http://matthewhudson.me/projects/device.js/) called device.js.

For responsive design there are a number of techniques available now that don't involve device detection (such as the picture element, examples [here](https://simpl.info/pictureart) and [here](https://simpl.info/picturetype)).

I've actually now removed the Device.js example from simpl.info – it's an application/tool rather than a feature of HTML, CSS or JavaScript.

**Comment by KrishPS** [comment]
Hi Sam,

Thanks a lot.
